// <auto-generated />
namespace PassionProjectN01649276.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tour));
        
        string IMigrationMetadata.Id
        {
            get { return "202406012214241_tour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
